using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using work;

namespace work.Pdf
{
    public static class FuelReportPdfGenerator
    {
        public static void Generate(List<Transaction> transactions, string adminEmail, DateTime from, DateTime to)
        {
            string fileName = $"Fuel_Report_{DateTime.Now:yyyyMMdd_HHmmss}.pdf";
            string filePath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), fileName);

            var groupedData = transactions
                .Where(t => t.DataTime >= from && t.DataTime <= to)
                .GroupBy(t => t.StationId)
                .OrderBy(g => g.Key)
                .ToList();

            var now = DateTime.Now;
            QuestPDF.Settings.License = LicenseType.Community;

            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(40);
                    page.DefaultTextStyle(x => x.FontSize(12));
                    page.PageColor(Colors.White);

                    page.Header().Row(r =>
                    {
                        r.RelativeItem().Height(25).Background(Colors.Red.Medium);
                    });

                    page.Content().Column(col =>
                    {
                        col.Spacing(10);

                        col.Item().Text("Fuel Report").Bold().FontSize(20).AlignCenter();

                        col.Item().Text($"Generated by: {adminEmail}").Bold();
                        col.Item().Text($"Date range: {from:yyyy-MM-dd} to {to:yyyy-MM-dd}");

                        col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                        if (!groupedData.Any())
                        {
                            col.Item().PaddingTop(10).Text("No data found for the selected period.").Italic();
                        }
                        else
                        {
                            foreach (var stationGroup in groupedData)
                            {
                                var stationId = stationGroup.Key;
                                col.Item().Text($"Station {stationId}").Bold().FontSize(16).FontColor(Colors.Blue.Darken2);

                                var pumpGroups = stationGroup
                                    .GroupBy(t => t.PumpId)
                                    .OrderBy(g => g.Key);

                                foreach (var pumpGroup in pumpGroups)
                                {
                                    var pumpId = pumpGroup.Key;
                                    var fuelType = pumpGroup.First().FuelType;
                                    double totalLiters = pumpGroup.Sum(t => t.QuantityLiters);
                                    decimal totalMoney = pumpGroup.Sum(t => t.Money);

                                    col.Item().PaddingLeft(10).Column(pumpCol =>
                                    {
                                        pumpCol.Item().Text($"Pump Id: {pumpId}").Bold();
                                        pumpCol.Item().Text($"Fuel Type: {fuelType}");
                                        pumpCol.Item().Text($"- Total Sold: {totalLiters:F2} L");
                                        pumpCol.Item().Text($"- Total Earned: {totalMoney:F2} zł.");
                                    });
                                }

                                col.Item().PaddingVertical(10).BorderBottom(1).BorderColor(Colors.Grey.Lighten2);
                            }
                        }

                        col.Item().AlignCenter().Text("End of Report").Italic();
                    });

                    page.Footer().Row(row =>
                    {
                        row.RelativeItem().Height(25).Background(Colors.Red.Medium);
                    });
                });
            });
            document.GeneratePdf(filePath);

            System.Diagnostics.Process.Start("explorer", filePath);
        }
    }
}
